version: "3.7"

networks:

  # network for services proxied by traefik
  frontend:
    ipam:
      config:
        - subnet: 172.31.0.0/24
        # gateway will be 172.31.0.1

secrets:
  plex_claim:
    file: secrets/plex_claim

volumes:
  plex:

services:

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    volumes:
      - $DOCKERDIR/nzbget:/config
      - $MEDIADIR/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget.entrypoints=lan

  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    restart: unless-stopped
    environment:
      ADVERTISE_IP: "https://plex.$DOMAINNAME"
      HOSTNAME: PlexServer
      PLEX_CLAIM: "/run/secrets/plex_claim"
      PLEX_GID: $PGID
      PLEX_UID: $PUID
      TZ:
    networks:
      - frontend
    ports:
      - "32400:32400/tcp" # main port for Plex Media Server
      - "32410:32410/udp" # for GDM discovery on the LAN
      - "32412-32414:32412-32414/udp" # for GDM discovery on the LAN
    volumes:
      - plex:/config
      - $MEDIADIR/Music:/data/music
      - $MEDIADIR/Movies:/data/movies
      - "$MEDIADIR/TV Shows:/data/tv"
    secrets:
      - plex_claim
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=lan
      - traefik.http.services.plex-docker.loadbalancer.server.port=32400

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MEDIADIR:/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=lan

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/sonarr:/config
      - "$MEDIADIR/TV Shows:/tv"
      - $MEDIADIR/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=lan

  traefik:
    image: traefik:v2.8
    container_name: traefik 
    restart: unless-stopped
    command:
      - --global.checknewversion=true
      - --global.sendanonymoususage=true
      - --api=true
      - --entrypoints.lan.address=:80
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.toasty.lan`)
      - --providers.docker.network=docker_frontend
      - --providers.file.directory=/providers
    environment:
      TZ:
    networks:
      frontend:
        ipv4_address: 172.31.0.254
    ports:
      - "80:80"
    volumes:
      - $DOCKERDIR/traefik/providers:/providers
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=lan
      - traefik.http.routers.traefik.service=api@internal

