version: "3.7"

networks:

  # network for services proxied by traefik
  frontend:
    ipam:
      config:
        - subnet: 172.31.0.0/24
        # gateway will be 172.31.0.1

secrets:
  namecheap_key:
    file: secrets/namecheap_key
  namecheap_user:
    file: secrets/namecheap_user
  plex_claim:
    file: secrets/plex_claim

volumes:
  plex:
  traefik-acme:

services:

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    volumes:
      - $DOCKERDIR/nzbget:/config
      - $MEDIADIR/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget.entrypoints=websecure

  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    restart: unless-stopped
    environment:
      ADVERTISE_IP: "https://plex.$DOMAIN"
      ALLOWED_NETWORKS: "172.31.0.0/24"
      HOSTNAME: PlexServer
      PLEX_CLAIM: "/run/secrets/plex_claim"
      PLEX_GID: $PGID
      PLEX_UID: $PUID
      TZ:
    networks:
      - frontend
    ports:
      - "32400:32400/tcp" # main port for Plex Media Server
      - "32410:32410/udp" # for GDM discovery on the LAN
      - "32412-32414:32412-32414/udp" # for GDM discovery on the LAN
    volumes:
      - plex:/config
      - $MEDIADIR/Music:/data/music
      - $MEDIADIR/Movies:/data/movies
      - "$MEDIADIR/TV Shows:/data/tv"
    secrets:
      - plex_claim
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.services.plex-docker.loadbalancer.server.port=32400

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MEDIADIR:/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PGID:
      PUID:
      TZ:
    networks:
      - frontend
    volumes:
      - $DOCKERDIR/sonarr:/config
      - "$MEDIADIR/TV Shows:/tv"
      - $MEDIADIR/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure

  traefik:
    image: traefik:v3.0
    container_name: traefik 
    restart: unless-stopped
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --api=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.portal.address=:8880
      - --entrypoints.portal.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certResolver=leresolver
      - --entrypoints.websecure.http.tls.domains[0].main=$DOMAIN
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAIN
      - --certificatesresolvers.leresolver.acme.email=admin@$DOMAIN
      - --certificatesresolvers.leresolver.acme.storage=/acme/acme.json
      - --certificatesresolvers.leresolver.acme.dnschallenge.provider=namecheap
      - --certificatesresolvers.leresolver.acme.dnschallenge.delaybeforecheck=90
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.$DOMAIN`)
      - --providers.docker.network=docker_frontend
      - --providers.file.directory=/config
    environment:
      NAMECHEAP_API_KEY_FILE: /run/secrets/namecheap_key
      NAMECHEAP_API_USER_FILE: /run/secrets/namecheap_user
      TZ:
    networks:
      frontend:
        ipv4_address: 172.31.0.254
    ports:
      - "80:80"
      - "443:443"
      - "8880:8880"
    volumes:
      - traefik-acme:/acme
      - $DOCKERDIR/traefik/config:/config
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    secrets:
      - namecheap_key
      - namecheap_user
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal

  unifi:
    user: unifi
    image: ghcr.io/jacobalberty/unifi-docker
    container_name: unifi
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
    environment:
      TZ:
    networks:
      frontend:
    volumes:
      - $DOCKERDIR/unifi:/unifi
    labels:
      - traefik.enable=true
      - traefik.http.routers.unifi.entrypoints=websecure
      - traefik.http.routers.unifi.service=unifi-docker
      - traefik.http.services.unifi-docker.loadbalancer.server.port=8443
      - traefik.http.services.unifi-docker.loadbalancer.server.scheme=https
      - traefik.http.services.unifi-docker.loadbalancer.serverstransport=unifi@file
      - traefik.http.routers.portal.rule=Host(`portal.$DOMAIN`)
      - traefik.http.routers.portal.entrypoints=websecure
      - traefik.http.routers.portal.service=portal-docker
      - traefik.http.services.portal-docker.loadbalancer.server.port=8880
      - traefik.http.services.portal-docker.loadbalancer.server.scheme=http
